export * from './home/home.component';
export * from './login/login.component';
export * from './universities/universities.component';
export * from './createuser/createuser.component';
export * from './createapplication/createapplication.component';
export * from './subjects/subjects.component';
export * from './help/help.component';
export * from './profile/profile.component';
export * from './chat/chat.component'
